# Generated by Django 4.2.3 on 2024-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
