# Generated by Django 4.2.3 on 2024-06-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_application_cv_application_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='title',
        ),
    ]
