# Generated by Django 4.2.3 on 2024-06-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_job_title_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
    ]
