# Generated by Django 4.2.3 on 2024-06-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_cv_alter_account_email_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email adress'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
